Make use of php://memory stream for Unit testing
yiisoft/proxy pull request #47
Opened 2022-07-05 08:11 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #42

2022-07-05 10:34 UTC, xepozz requested changes

2022-07-05 10:34 UTC, xepozz commented on src/ClassCache.php
> +        $flags = $this->cachePath === 'php://memory' ? LOCK_EX : 0;
Don't you want vise versa?

2022-07-05 11:30 UTC, arogachev commented on src/ClassCache.php
> +        $flags = $this->cachePath === 'php://memory' ? LOCK_EX : 0;
Ooops,,, Yes. But at the end it works fine with exclusive lock so I reverted these changes completely.

2022-07-05 11:40 UTC, arogachev commented on src/ClassCache.php
> +        if ($this->cachePath === 'php://memory') {
Just noticed that every time memory stream is used, a bunch of proxy files is left after running tests (location is repo root folder). :thinking:

2022-07-05 11:53 UTC, arogachev commented on src/ClassCache.php
> +        $flags = $this->cachePath === 'php://memory' ? LOCK_EX : 0;
Nope, there was another error. Reverted and fixed.

2022-07-07 05:32 UTC, arogachev commented
https://github.com/yiisoft/proxy/issues/42#issuecomment-1177092160

2022-07-07 05:32 UTC, closed without merging